### ISSUE TITLE
Pyjolokia never close requests

### ISSUE THREAD

**Issue by deniszh** [cwood/pyjolokia#5]
pyjolokia runs http request through urllib2 internally, but never closes connection, which cause tons of TIME_WAIT sockets when you running it constantly.

**Comment by gothicx** [comment]
Hi,

This actually is not working when the URL does not work, e.g: connection refused.
As the code inside the try statement is not executed, it doesn't know any responseStream.

j4p = Jolokia('http://localhost:7778/jolokia/')

Traceback (most recent call last):
  File "jolokia.py", line 49, in <module>
    main()
  File "jolokia.py", line 38, in main
    data = j4p.getRequests()
  File "pyjolokia.py", line 184, in getRequests
    response = self.__getJson()
  File "pyjolokia.py", line 139, in __getJson
    responseStream.close()
UnboundLocalError: local variable 'responseStream' referenced before assignment

**Comment by gothicx** [comment]
Maybe this way?

        try:
            request = Request(self.url, jdata,
                              {'content-type': 'application/json'})

            if authheader:
                request.add_header("Authorization", authheader)

            responseStream = urlopen(request, timeout=self.timeout)
            **try:
                jsonData = responseStream.read()
            finally:
                responseStream.close()**
        except Exception as e:
            raise JolokiaError('Could not connect. Got error %s' % (e))
