### ISSUE TITLE
The Jolokia reqConfig isn't documented

### ISSUE THREAD

**Issue by pcn** [cwood/pyjolokia#8]
I just found that in order to get MemoryPool items, you need to enable the ignoreErrors flag on the Jolokia object in order for that to be sent to the proxy.

I've ended up creating the proxy, then doing something like the following in order to :

```
    jconn.reqConfig['ignoreErrors'] = True
    jconn.add_request(...)
    [...]
    data = jconn.getRequests()
```

I don't see documentation on how this is intended to be used, so I'm asking for some guidance, specifically whether this is the intended use of the objects reqConfig?

Thanks!

**Comment by cwood** [comment]
That is probably fine to use. I am not planning on changing any of the internal apis anytime soon. This whole thing probabaly needs a refactoring.

**Comment by pcn** [comment]
Cool, thanks.
