### ISSUE TITLE
Output serialization

### ISSUE THREAD

**Issue by panda87** [cwood/pyjolokia#9]
Hi

I'm working with the Jolokia as proxy mode and I have a few queries that I prefer to use wildcard, for example,
mbean: "kafka.log:type=Log,name=LogEndOffset,*"
The result of this query is list of my topic with their offsets as Value.

My problem is, that the output is written as one and long object serialized instead of many objects as the number of the topics.

Can you please add the ability to slice the object to more than one dict object?

Thanks
D.

**Comment by cwood** [comment]
pyjolokia doesnt make any changes to data types or try to sort. This is soemthing that the jolika server does. If you want this feature you can try to add it. But this seems like a issue with jolokia and not so much this client lib.

**Comment by panda87** [comment]
Ok, thanks for the info @cwood
